### ISSUE TITLE
QuoteItem binding to ViewModel

### ISSUE THREAD

**Issue by TylerTrahan** [TylerTrahan/HydrotestCentral#1]
I am currently working on the Quote building system. It consists of selecting a Quote Header from the top datagrid, which populates 1 or multiple tabs which each have their own datagrid, which corresponds to QuoteItems, a table in the database. I need help binding the QuoteItems where any changes will be saved to the database and the view updated.

**Comment by lukele1607** [comment]
I did quick fix in
https://github.com/lukele1607/HydrotestCentral
You can take a look. In my code, I have just saved "descr" to the database .

**Comment by shiva0603** [comment]
Is the delete function working ? Sure will look into it !

**Comment by lukele1607** [comment]
No. Only binding the QuoteItem and the "**descr**" column changes will be saved to the database and the view updated.
For delete function, you could handle QuoteItems.CollectionChanged += QuoteItems_CollectionChanged; in QuoteItemsVM.cs. When 1 row deleted, ObservableCollection<QuoteItemVM> QuoteItems will fire event, and you could hanlde and update db

**Comment by lukele1607** [comment]
@shiva0603 I have just pushed code delete QuoteItem, You can select a row and use delete key on keyboard to delete. My code just simple code, so it will not nice.

**Comment by shiva0603** [comment]
Delete function works by pressing delete button on the form. Is that
happening ?

Thanks,
Sivashankari

**Comment by lukele1607** [comment]
No. Select QuoteItem you want to delete then use delete key on keyboard to delete.

**Comment by shiva0603** [comment]
Okay! Let’s have a call tomorrow and discuss the functionalities before I
proceed!

Thanks,
Shiva

**Comment by shiva0603** [comment]
Oh just wanted to let you know I have made delete function for quote header
item & not for quote item. Can you check whether that works fine ?

**Comment by lukele1607** [comment]
@shiva0603  I have just check delete function for quote header. It seems working fine. I think you should implement all operations related to database like CRUD in a service or Repository

**Comment by shiva0603** [comment]
Sure I can implement those! Let’s have a call at 11am and I just need to
clarify few things. 11am CST fine?

Thanks,
Sivashankari

**Comment by lukele1607** [comment]
I am not the developer of this project. But you can contact me via skype: letrongluc or email lukele1607@gmail.com
I can not have a call but text is ok

**Comment by shiva0603** [comment]
Fine I will draft all my questions to your email id and get it clarified!

Thanks,
Sivashankari
